// <auto-generated />
namespace LauncherServer.Migrations.LauncherDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addComputer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addComputer));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051747257_addComputer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
