// <auto-generated />
namespace LauncherServer.Migrations.LauncherDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_using : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_using));
        
        string IMigrationMetadata.Id
        {
            get { return "201705301427520_add_using"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
